on:
  push:
    branches: main

name: Build and deploy book to GitHub Pages

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v6.0.1

      - name: Install and setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
          # TODO: consider pinning a version
          # with:
          #   version: 1.6.39 

      # TODO uncomment if need R
      # - name: Setup R
      #   uses: r-lib/actions/setup-r@v2
      #   with:
      #     # pins an R version
      #     r-version: 4.5.1
      #     # fetch pre-built binaries from Posit repo
      #     use-public-rspm: true

      # TODO: specify dependencies in DESCRIPTION file
      # - uses: r-lib/actions/setup-r@v2
      #   with:
      #     use-public-rspm: true

      - name: Render book
        run: |
          quarto render

      - name: Upload artifacts to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_book"

  deploy:

    needs: build

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
